### ISSUE TITLE
Had to manually upgrade ipykernel to run notebook locally

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/kingfisher-colab#34]
When running a notebook locally, I got this error:
```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback (<zmq.sugar.socket.Socket object at 0x7fd311ad0db0>, <function wrap.<locals>.null_wrapper at 0x7fd311aa96a8>)
Traceback (most recent call last):
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/vagrant/open-contracting/kingfisher-colab/.ve/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

These issues seem related:
https://github.com/ipython/ipython/issues/11258
https://github.com/ipython/ipykernel/issues/335

Upgrading ipykernel fixes it.

```
pip install --upgrade ipykernel
```

The current version of `ipykernel` is pinned by the `google-colab` library, so I'm not sure what a good fix for this would look like.

**Comment by jpmckinney** [comment]
I think all we can do is documentation, and adding that `pip` command in the notebooks we share.
